name = "access-decoder-worker"
main = "src/index.js"
compatibility_date = "2024-02-08"

[vars]
# LOGIN => LOGIN URL
# DOMAIN => https://YOURSDOMAIN.cloudflareaccess.com
# AUD => AUDIENCE TAG from CF ACCESS APPLICATION